name = "masanice"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "211.230.110.231:50008"
UUID = "fc44042f-2e0c-49aa-8fc7-d0173e2d10f5"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
